addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.28")
addSbtPlugin("org.portable-scala" % "sbt-crossproject"         % "0.6.0" )
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.0" )
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"             % "0.14.9")
addSbtPlugin("com.permutive"      % "sbt-liquibase"            % "1.1.0" )
